"""
Simple column names from the yfinance api library
"""

balancesheetref = (
    "Intangible Assets",
    "Capital Surplus",
    'Total Liab',
    'Total Stockholder Equity',
    "Minority Interest",
    'Other Current Liab',
    'Total Assets',
    "Other Current Assets",
    'Common Stock',
    'Retained Earnings',
    'Other Liab',
    "Good Will",
    'Treasury Stock',
    'Other Assets',
    'Cash',
    'Total Current Liabilities',
    'Other Stockholder Equity',
    'Property Plant Equipment',
    'Total Current Assets',
    'Long Term Investments',
    'Net Tangible Assets',
    'Short Term Investments',
    'Long Term Debt',
    'Inventory',
    'Accounts Payable',
    "Deferred Long Term Asset Charges",
    "Net Receivables",
    'Short Long Term Debt',
)

financialsref = (
    'Research Development',
    'Income Before Tax',
    'Net Income',
    'Selling General Administrative',
    'Gross Profit',
    'Ebit',
    'Operating Income',
    'Other Operating Expenses',
    'Interest Expense',
    'Income Tax Expense',
    'Total Revenue',
    'Total Operating Expenses',
    'Cost Of Revenue',
    'Total Other Income Expense Net',
    'Discontinued Operations',
    'Net Income From Continuing Ops',
    'Net Income Applicable To Common Shares',
)

cashflowref = (
    'Investments',
    'Change To Liabilities',
    'Total Cashflows From Investing Activities',
    'Net Borrowings',
    'Total Cash From Financing Activities',
    'Change To Operating Activities',
    'Change In Cash',
    'Repurchase Of Stock',
    'Total Cash From Operating Activities',
    'Depreciation',
    'Other Cashflows From Investing Activities',
    'Dividends Paid',
    'Change To Inventory',
    'Change To Account Receivables',
    'Other Cashflows From Financing Activities',
    'Change To Net Income',
    'Capital Expenditures',
    'Issuance Of Stock',
)

earningsref = (
    'Revenue',
    'Earnings',
)

inforef = (
    'address1',
    'city',
    'state',
    'zip',
    'country',
    'phone',
    'website',
    'industry',
    'industryKey',
    'industryDisp',
    'sector',
    'sectorKey',
    'sectorDisp',
    'longBusinessSummary',
    'fullTimeEmployees',
    'companyOfficers',
    'auditRisk',
    'boardRisk',
    'compensationRisk',
    'shareHolderRightsRisk',
    'overallRisk',
    'governanceEpochDate',
    'compensationAsOfEpochDate',
    'irWebsite',
    'maxAge',
    'priceHint',
    'previousClose',
    'open',
    'dayLow',
    'dayHigh',
    'regularMarketPreviousClose',
    'regularMarketOpen',
    'regularMarketDayLow',
    'regularMarketDayHigh',
    'dividendRate',
    'dividendYield',
    'exDividendDate',
    'payoutRatio',
    'fiveYearAvgDividendYield',
    'beta',
    'trailingPE',
    'forwardPE',
    'volume',
    'regularMarketVolume',
    'averageVolume',
    'averageVolume10days',
    'averageDailyVolume10Day',
    'bid',
    'ask',
    'bidSize',
    'askSize',
    'marketCap',
    'fiftyTwoWeekLow',
    'fiftyTwoWeekHigh',
    'priceToSalesTrailing12Months',
    'fiftyDayAverage',
    'twoHundredDayAverage',
    'trailingAnnualDividendRate',
    'trailingAnnualDividendYield',
    'currency',
    'enterpriseValue',
    'profitMargins',
    'floatShares',
    'sharesOutstanding',
    'sharesShort',
    'sharesShortPriorMonth',
    'sharesShortPreviousMonthDate',
    'dateShortInterest',
    'sharesPercentSharesOut',
    'heldPercentInsiders',
    'heldPercentInstitutions',
    'shortRatio',
    'impliedSharesOutstanding',
    'bookValue',
    'priceToBook',
    'lastFiscalYearEnd',
    'nextFiscalYearEnd',
    'mostRecentQuarter',
    'earningsQuarterlyGrowth',
    'netIncomeToCommon',
    'trailingEps',
    'forwardEps',
    'pegRatio',
    'lastSplitFactor',
    'lastSplitDate',
    'enterpriseToRevenue',
    '52WeekChange',
    'SandP52WeekChange',
    'lastDividendValue',
    'lastDividendDate',
    'exchange',
    'quoteType',
    'symbol',
    'underlyingSymbol',
    'shortName',
    'longName',
    'firstTradeDateEpochUtc',
    'timeZoneFullName',
    'timeZoneShortName',
    'uuid',
    'messageBoardId',
    'gmtOffSetMilliseconds',
    'currentPrice',
    'targetHighPrice',
    'targetLowPrice',
    'targetMeanPrice',
    'targetMedianPrice',
    'recommendationMean',
    'recommendationKey',
    'numberOfAnalystOpinions',
    'totalCash',
    'totalCashPerShare',
    'totalDebt',
    'totalRevenue',
    'revenuePerShare',
    'returnOnAssets',
    'returnOnEquity',
    'operatingCashflow',
    'earningsGrowth',
    'revenueGrowth',
    'operatingMargins',
    'financialCurrency',
    'trailingPegRatio'
)

everyref = (
    "Intangible Assets",
    "Capital Surplus",
    'Total Liab',
    'Total Stockholder Equity',
    "Minority Interest",
    'Other Current Liab',
    'Total Assets',
    "Other Current Assets",
    'Common Stock',
    'Retained Earnings',
    'Other Liab',
    "Good Will",
    'Treasury Stock',
    'Other Assets',
    'Cash',
    'Total Current Liabilities',
    'Other Stockholder Equity',
    'Property Plant Equipment',
    'Total Current Assets',
    'Long Term Investments',
    'Net Tangible Assets',
    'Short Term Investments',
    'Long Term Debt',
    'Inventory',
    'Accounts Payable',
    "Deferred Long Term Asset Charges",
    "Net Receivables",
    'Short Long Term Debt',
    'Research Development',
    'Income Before Tax',
    'Net Income',
    'Selling General Administrative',
    'Gross Profit',
    'Ebit',
    'Operating Income',
    'Other Operating Expenses',
    'Interest Expense',
    'Income Tax Expense',
    'Total Revenue',
    'Total Operating Expenses',
    'Cost Of Revenue',
    'Total Other Income Expense Net',
    'Discontinued Operations',
    'Net Income From Continuing Ops',
    'Net Income Applicable To Common Shares',
    'Investments',
    'Change To Liabilities',
    'Total Cashflows From Investing Activities',
    'Net Borrowings',
    'Total Cash From Financing Activities',
    'Change To Operating Activities',
    'Change In Cash',
    'Repurchase Of Stock',
    'Total Cash From Operating Activities',
    'Depreciation',
    'Other Cashflows From Investing Activities',
    'Dividends Paid',
    'Change To Inventory',
    'Change To Account Receivables',
    'Other Cashflows From Financing Activities',
    'Change To Net Income',
    'Capital Expenditures',
    'Issuance Of Stock',
    'Revenue',
    'Earnings',
)

